services:

  sodor24-server:
    container_name: sodor24-server
    image: sodor24-server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://sodor24-db:3306/sodor24db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_REDIS_HOST: redis
      APP_SERVER_HOST: http://localhost:8181
      APP_CLIENT_HOST: http://localhost:3000
      ZARINPAL_SERVER_HOST: https://sandbox.zarinpal.com
      ZARINPAL_MERCHANT_ID: 7007f58a-3ec5-4ea6-a414-5849591ba0a7
      RABBITMQ_HOST: sodor24-rabbitmq
    depends_on:
      sodor24-db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8181:8181"
    restart: unless-stopped
    networks:
      - sodor24-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - sodor24-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  sodor24-db:
    image: mysql:8.0
    container_name: sodor24-db
    environment:
      MYSQL_DATABASE: sodor24db
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - sodor24-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - sodor24-network

  rabbitmq:
    image: rabbitmq:3.10.5-management
    container_name: sodor24-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - sodor24-rabbitmq:/var/lib/rabbitmq
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sodor24-network

  signature-service:
    image: alizamanian/signature-service:v1.0.0
    container_name: signature-service
    ports:
      - "8585:8585"
    depends_on:
      sodor24-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://sodor24-db:3306/signaturedb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    restart: unless-stopped
    networks:
      - sodor24-network

volumes:
  sodor24-db:
  sodor24-rabbitmq:

networks:
  sodor24-network:
    driver: bridge